#!/bin/bash

# adduser --disabled-password --gecos '' celeryuser

#if ! [ -x "$(command -v pipenv)" ]; then
#  pip install pipenv
#fi
#
#if [ -n "$DEBUG" ]; then
#  pipenv install -r requirements.txt
#else
#  pipenv install -r requirements.txt
#fi

celery -A spelunker_api.app.celery worker&
python manage.py init

exec "$@"
