#!/bin/bash

FIRST_RUN=true

until (echo 2>/dev/null > /dev/tcp/persistent_db/5432)
do
  echo "Startup: Waiting for Postgres..."
  if $FIRST_RUN; then
    echo "\tTo track progress, run:"
    echo "\tdocker-compose logs -f persistent_db"
    FIRST_RUN=false
  fi
  sleep 1
done

until (echo 2>/dev/null > /dev/tcp/persistent_redis/6379)
do
  echo "Startup: Waiting for Redis..."
  if $FIRST_RUN; then
    echo "\tTo track progress, run:"
    echo "\tdocker-compose logs -f persistent_redis"
    FIRST_RUN=false
  fi
  sleep 1
done

exec "$@"
